import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ContactIcon, TestIcon } from "@assets/icons";
import { img_mobile, img_mongodb, img_certficate } from "@assets/images";
import { Title } from "@components/shared";
import {
  HeroSection,
  AboutMeSection,
  WhatIdoSection,
  SkillsSection,
  ProjectSection,
  CertificatesSection,
} from "@components/home";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Neljohn Cerera Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* HEADER */}
        {/* <header>
          <div>
            <MyLogo classname="w-16 h-16" fill="white" />
            <button>
              <MenuIcon classname="w-10 h-10 text-white" />
            </button>
          </div>
          <nav>
            <ul>
              <li className="">Home</li>
              <li>Projects</li>
              <li>What i do</li>
              <li>About Me</li>
              <li>Contact me</li>
            </ul>
            <button>
              Download CV <DownloadIcon />
            </button>
          </nav>
        </header> */}
        {/* MAIN */}
        <main>
          {/* SECTION HERO */}
          <HeroSection />

          {/* SECTION ABOUT ME */}
          <AboutMeSection />

          <section>
            {/* SECTION WHAT I DO */}
            <WhatIdoSection />
            {/* SECTION SKILLS */}
            <SkillsSection />
          </section>

          {/* SECTION PROJECTS */}
          <ProjectSection />

          {/* SECTION CERTIFICATES */}
          <CertificatesSection />

          {/* SECTION CONTACT ME */}
          <section>
            {/* <ContactIcon /> */}
            <Title.Section>CONTACT ME</Title.Section>
            <p>
              Mobile # : <span>09457065593</span>
            </p>
            <p>
              Email <span>neljohncerera.github@gmailc.om</span>
            </p>
          </section>
        </main>
        {/* FOOTER */}
        <footer>
          <h3>FOOTER</h3>
        </footer>
      </>
    </>
  );
};

export default Home;
