import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  ContactIcon,
  DownloadIcon,
  FacebookIcon,
  GithubIcon,
  LinkinIcon,
  MenuIcon,
  MyLogo,
  TestIcon,
} from "../src/assets/icons";
import { img_mobile, img_mongodb, img_certficate } from "../src/assets/images";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Neljohn Cerera Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* HEADER */}
        <header>
          <div>
            <MyLogo classname="w-16 h-16" fill="white" />
            <button>
              <MenuIcon classname="w-10 h-10 text-white" />
            </button>
          </div>
          <nav>
            <ul>
              <li>Home</li>
              <li>Projects</li>
              <li>What i do</li>
              <li>About Me</li>
              <li>Contact me</li>
            </ul>
            <button>
              Download CV <DownloadIcon />
            </button>
          </nav>
        </header>
        {/* MAIN */}
        <main>
          {/* SECTION HERO */}
          <section>
            <div>
              <h1>HELLO</h1>
              <h2>I'm</h2>
              <h2>
                Neljohn <span>Cerera</span>
              </h2>
              <p>Web Developer</p>
            </div>
            <div>
              <p>Follow me</p>
              <div></div>
              <FacebookIcon />
              <GithubIcon />
              <LinkinIcon />
            </div>
          </section>
          {/* SECTION What i do & skills */}
          <section>
            {/* WHAT I DO */}
            <div className="whatido">
              <h3>WHAT I DO</h3>
              <div>
                <div>
                  <TestIcon />
                  <p>Responsive Design</p>
                </div>
                <div>
                  <TestIcon />
                  <p>Mobile First</p>
                </div>
                <div>
                  <TestIcon />
                  <p>Design to Code</p>
                </div>
                <div>
                  <TestIcon />
                  <p>Design to Code</p>
                </div>
              </div>
              <div>
                <span>LINE</span>
              </div>
            </div>
            {/* SKILLS */}
            <div className="skills">
              <h3>SKILLS</h3>
              <Image
                src={img_mongodb}
                alt="Mongo db skills image"
                width={200}
                height={200}
              />
              <Image
                src={img_mongodb}
                alt="Mongo db skills image"
                width={200}
                height={200}
              />
              <Image
                src={img_mongodb}
                alt="Mongo db skills image"
                width={200}
                height={200}
              />
              <Image
                src={img_mongodb}
                alt="Mongo db skills image"
                width={200}
                height={200}
              />{" "}
              <Image
                src={img_mongodb}
                alt="Mongo db skills image"
                width={200}
                height={200}
              />
              <Image
                src={img_mongodb}
                alt="Mongo db skills image"
                width={200}
                height={200}
              />
              <Image
                src={img_mongodb}
                alt="Mongo db skills image"
                width={200}
                height={200}
              />
            </div>
          </section>
          {/* SECTION PROJECTS */}
          <section>
            <h3>PROJECTS</h3>
            <div>
              <Image
                src={img_mobile}
                alt="Mongo db skills image"
                width={400}
                height={400}
              />
              <div>
                <h4>Library Book Reservation</h4>
                <p>Technology Used</p>
                <ul>
                  <li>Next js Typescript</li>
                  <li>Tailwind css</li>
                  <li>Graphql</li>
                  <li>Apollo Express Server</li>
                  <li>React native Expo</li>
                  <li>Postgres</li>
                </ul>
              </div>
            </div>
            <button>View all</button>
          </section>
          {/* SECTION CERTIFICATES */}
          <section>
            <h3>CERTIFICATES</h3>
            <h4>The Front End Career Path</h4>
            <Image
              src={img_certficate}
              alt="Certificate"
              width={400}
              height={400}
            />
            <button>View all</button>
          </section>
          {/* SECTION CONTACT ME */}
          <section>
            <ContactIcon />
            <h3>CONTACT ME</h3>
            <p>
              Mobile # : <span>09457065593</span>
            </p>
            <p>
              Email <span>neljohncerera.github@gmailc.om</span>
            </p>
          </section>
        </main>
        {/* FOOTER */}
        <footer>
          <h3>FOOTER</h3>
        </footer>
      </main>
    </>
  );
};

export default Home;
