import CertificatesSection from "@components/certificates";

import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Neljohn Cerera Portfolio Certificates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CertificatesSection />
      </main>
    </>
  );
};

export default Home;
